### ISSUE TITLE
No Documentation on actually using the middleware

### ISSUE THREAD

**Issue by stijink** [emileber/axios-middleware#9]
Hey,

nice work you've done here. I would like start using this module. I could find a lot of good examples within the documentation how to configure the middleware. But right now i'm not sure how to actually use the middleware with axios to perform http calls. 

And I could not find any examples on this topic in the documentation. Maybe you could add some actual examples.

Thanks,
Stephan

**Comment by emileber** [comment]
The middleware doesn't do HTTP calls on its own, unless you tell it to.

The only thing needed to start using this module is to instantiate a service instance passing it the axios instance you're using within your app.

The [simplest use-case](https://emileber.github.io/axios-middleware/#/?id=simplest-use-case) covers that, and the [service module example](https://emileber.github.io/axios-middleware/#/examples/service) shows another common use-case.

Then, once instantiated, you just need to use axios as you would and the middlewares will be called.

```javascript
import axios from 'axios';
import { HttpMiddlewareService } from 'axios-middleware';

const service = new HttpMiddlewareService(axios);

service.register({
    onRequest(config) {
        console.log('onRequest');
        return config;
    },
    onSync(promise) {
		console.log('onSync');
        return promise;
    },
    onResponse(response) {
        console.log('onResponse');
        return response;
    }
});

console.log('Ready to fetch.');


// Just use axios like you would normally.
axios('https://jsonplaceholder.typicode.com/posts/1')
  .then(({ data }) => console.log('Received:', data));
```

It should output the following:

```

Ready to fetch.
onRequest
onSync
onResponse
Received: {userId: 1, id: 1, title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit", body: "quia et suscipit↵suscipit recusandae consequuntur …strum rerum est autem sunt rem eveniet architecto"}
```

Here's a [snippet](https://jsfiddle.net/m8fxu9hs/1/) showing it working.

**Comment by emileber** [comment]
The [tests](https://github.com/emileber/axios-middleware/blob/679302ce7c35a156115b36cc0f9b52b79ae33988/test/specs/service.spec.js) also have great examples of the expected behaviour.

**Comment by emileber** [comment]
I could definitely make it clearer in the documentation, and maybe add an example of a middleware spec.

**Comment by stijink** [comment]
Thank you. That helps me to clear things up 👍

**Comment by emileber** [comment]
I added the snippet to the official documentation, in addition to a spec example in the PR #10
